<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DyeDurhamLexicalSortEngine.Domain\DyeDurhamLexicalSortEngine.Domain.csproj" />
    <ProjectReference Include="..\DyeDurhamLexicalSortEngine.Infrastructure\DyeDurhamLexicalSortEngine.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="unsorted-names-list.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
